exclude: '^docs/conf.py'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  # whitespace
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: mixed-line-ending
    args: ['--fix=lf']
    exclude: '.*\.(svg)$'
  - id: check-byte-order-marker
  # file format and permissions
  - id: check-ast
  - id: check-json
  - id: check-xml
  - id: check-yaml
    files: .*\.(yaml|yml)$
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  # git
  - id: check-shebang-scripts-are-executable
  - id: check-added-large-files
  - id: check-case-conflict
  - id: detect-private-key
  # python
  - id: debug-statements
  - id: check-docstring-first
  - id: name-tests-test
  - id: requirements-txt-fixer
  - id: double-quote-string-fixer
  - id: fix-encoding-pragma

- repo: https://github.com/PyCQA/bandit
  rev: 1.7.4
  hooks:
    - id: bandit

- repo: https://github.com/tox-dev/tox-ini-fmt
  rev: 0.5.2
  hooks:
    - id: tox-ini-fmt

- repo: https://opendev.org/openstack/bashate
  rev: 2.1.0
  hooks:
    - id: bashate
      args: ["--max-line-length", "150"]

- repo: https://github.com/PyCQA/isort
  rev: 5.11.5
  hooks:
  - id: isort

- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.3.1
  hooks:
    - id: remove-tabs
      exclude: '.*\.(svg)$'

- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: 'v1.7.0'
  hooks:
    - id: autopep8


- repo: https://github.com/PyCQA/flake8
  rev: 5.0.4
  hooks:
  - id: flake8

# Check for misspells in documentation files:
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.5
  hooks:
  - id: codespell

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.11.1'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
